### ISSUE TITLE
User dapat meminjam mobil yang terpinjam

### ISSUE THREAD

**Issue by grikomsn** [ok-google/struktur_data#1]
Periksa [bagian pengecekan pencarian mobil](https://github.com/ok-google/struktur_data/blob/master/Modul1/user.h#L30) saat user akan meminjam mobil. Tambahkan logika untuk menampilkan mobil yang belum terpinjam.

Update: coba fix issue dengan commit 👍

**Comment by ok-google** [comment]
Done
